
import { TermuxPackage } from './types';

export const INITIAL_PACKAGES: TermuxPackage[] = [
  // ==========================================
  // PKG - SYSTEM & SHELL (25)
  // ==========================================
  { id: 'pkg-1', name: 'zsh', category: 'System', source: 'pkg', description: 'Shell interaktif yang sangat dapat dikustomisasi.', installCommand: 'pkg install zsh', isPopular: true },
  { id: 'pkg-2', name: 'fish', category: 'System', source: 'pkg', description: 'Shell ramah pengguna yang fokus pada autosuggestion.', installCommand: 'pkg install fish' },
  { id: 'pkg-3', name: 'proot', category: 'System', source: 'pkg', description: 'Emulasi chroot, bind mount, dan binfmt_misc.', installCommand: 'pkg install proot' },
  { id: 'pkg-4', name: 'proot-distro', category: 'System', source: 'pkg', description: 'Alat untuk mengelola distribusi Linux di dalam Termux.', installCommand: 'pkg install proot-distro', isPopular: true },
  { id: 'pkg-5', name: 'termux-api', category: 'System', source: 'pkg', description: 'Akses fitur hardware Android melalui baris perintah.', installCommand: 'pkg install termux-api', isPopular: true },
  { id: 'pkg-6', name: 'termux-services', category: 'System', source: 'pkg', description: 'Sistem manajemen layanan (seperti systemd) untuk Termux.', installCommand: 'pkg install termux-services' },
  { id: 'pkg-7', name: 'termux-exec', category: 'System', source: 'pkg', description: 'Menangani shebang baris perintah secara otomatis.', installCommand: 'pkg install termux-exec' },
  { id: 'pkg-8', name: 'starship', category: 'System', source: 'pkg', description: 'Prompt shell minimal, sangat cepat, dan dapat dikustomisasi.', installCommand: 'pkg install starship' },
  { id: 'pkg-9', name: 'busybox', category: 'System', source: 'pkg', description: 'Swiss Army Knife dari utilitas Unix tertanam.', installCommand: 'pkg install busybox' },
  { id: 'pkg-10', name: 'debianutils', category: 'System', source: 'pkg', description: 'Utilitas spesifik Debian seperti run-parts.', installCommand: 'pkg install debianutils' },
  { id: 'pkg-11', name: 'coreutils', category: 'System', source: 'pkg', description: 'Utilitas inti GNU (ls, cp, mv, dll).', installCommand: 'pkg install coreutils' },
  { id: 'pkg-12', name: 'util-linux', category: 'System', source: 'pkg', description: 'Kumpulan utilitas sistem Linux yang penting.', installCommand: 'pkg install util-linux' },
  { id: 'pkg-13', name: 'findutils', category: 'System', source: 'pkg', description: 'Utilitas pencarian file GNU (find, xargs).', installCommand: 'pkg install findutils' },
  { id: 'pkg-14', name: 'grep', category: 'System', source: 'pkg', description: 'Alat pencarian pola teks yang kuat.', installCommand: 'pkg install grep' },
  { id: 'pkg-15', name: 'sed', category: 'System', source: 'pkg', description: 'Stream editor untuk memfilter dan mengubah teks.', installCommand: 'pkg install sed' },
  { id: 'pkg-16', name: 'gawk', category: 'System', source: 'pkg', description: 'Bahasa pemrograman pengolah pola teks.', installCommand: 'pkg install gawk' },
  { id: 'pkg-17', name: 'bash', category: 'System', source: 'pkg', description: 'Shell standar GNU yang kompatibel dengan sh.', installCommand: 'pkg install bash' },
  { id: 'pkg-18', name: 'dash', category: 'System', source: 'pkg', description: 'Shell POSIX yang cepat dan minimalis.', installCommand: 'pkg install dash' },
  { id: 'pkg-19', name: 'tsu', category: 'System', source: 'pkg', description: 'Wrapper su untuk Termux (memerlukan root).', installCommand: 'pkg install tsu' },
  { id: 'pkg-20', name: 'sudo', category: 'System', source: 'pkg', description: 'Menjalankan perintah sebagai user lain/root.', installCommand: 'pkg install sudo' },
  { id: 'pkg-21', name: 'man', category: 'System', source: 'pkg', description: 'Sistem dokumentasi manual perintah Linux.', installCommand: 'pkg install man' },
  { id: 'pkg-22', name: 'texinfo', category: 'System', source: 'pkg', description: 'Sistem dokumentasi GNU lainnya.', installCommand: 'pkg install texinfo' },
  { id: 'pkg-23', name: 'pcre', category: 'System', source: 'pkg', description: 'Library Perl Compatible Regular Expressions.', installCommand: 'pkg install pcre' },
  { id: 'pkg-24', name: 'attr', category: 'System', source: 'pkg', description: 'Alat untuk memanipulasi atribut file filesystem.', installCommand: 'pkg install attr' },
  { id: 'pkg-25', name: 'acl', category: 'System', source: 'pkg', description: 'Access Control Lists untuk manajemen izin file.', installCommand: 'pkg install acl' },

  // ==========================================
  // PKG - EDITORS (15)
  // ==========================================
  { id: 'pkg-26', name: 'nano', category: 'Editor', source: 'pkg', description: 'Editor teks terminal yang ramah pengguna.', installCommand: 'pkg install nano', isPopular: true },
  { id: 'pkg-27', name: 'vim', category: 'Editor', source: 'pkg', description: 'Editor teks legendaris dengan mode perintah.', installCommand: 'pkg install vim', isPopular: true },
  { id: 'pkg-28', name: 'neovim', category: 'Editor', source: 'pkg', description: 'Vim modern yang lebih cepat dan mendukung Lua.', installCommand: 'pkg install neovim', isPopular: true },
  { id: 'pkg-29', name: 'micro', category: 'Editor', source: 'pkg', description: 'Editor teks modern dengan pintasan gaya Windows.', installCommand: 'pkg install micro', isPopular: true },
  { id: 'pkg-30', name: 'emacs', category: 'Editor', source: 'pkg', description: 'Sistem komputasi lengkap yang menyamar jadi editor.', installCommand: 'pkg install emacs' },
  { id: 'pkg-31', name: 'mg', category: 'Editor', source: 'pkg', description: 'Emacs yang sangat ringan dan cepat.', installCommand: 'pkg install mg' },
  { id: 'pkg-32', name: 'joe', category: 'Editor', source: 'pkg', description: 'Editor teks berbasis terminal yang kuat dan mudah.', installCommand: 'pkg install joe' },
  { id: 'pkg-33', name: 'jed', category: 'Editor', source: 'pkg', description: 'Editor teks kecil berbasis S-Lang library.', installCommand: 'pkg install jed' },
  { id: 'pkg-34', name: 'hexcurse', category: 'Editor', source: 'pkg', description: 'Editor hexadesimal berbasis ncurses.', installCommand: 'pkg install hexcurse' },
  { id: 'pkg-35', name: 'hexer', category: 'Editor', source: 'pkg', description: 'Editor biner dengan antarmuka mirip Vi.', installCommand: 'pkg install hexer' },
  { id: 'pkg-36', name: 'kakoune', category: 'Editor', source: 'pkg', description: 'Editor modal yang terinspirasi dari Vi dengan seleksi berganda.', installCommand: 'pkg install kakoune' },
  { id: 'pkg-37', name: 'jupp', category: 'Editor', source: 'pkg', description: 'Turunan dari editor JOE yang klasik.', installCommand: 'pkg install jupp' },
  { id: 'pkg-38', name: 'helix', category: 'Editor', source: 'pkg', description: 'Editor teks modal modern yang ditulis dalam Rust.', installCommand: 'pkg install helix' },
  { id: 'pkg-39', name: 'vifm', category: 'Editor', source: 'pkg', description: 'Manajer file berbasis ncurses dengan keybinding Vi.', installCommand: 'pkg install vifm' },
  { id: 'pkg-40', name: 'ranger', category: 'Editor', source: 'pkg', description: 'Manajer file berbasis terminal dengan gaya kolom.', installCommand: 'pkg install ranger' },

  // ==========================================
  // PKG - DEVELOPMENT (30)
  // ==========================================
  { id: 'pkg-41', name: 'python', category: 'Development', source: 'pkg', description: 'Interpreter bahasa pemrograman Python 3.', installCommand: 'pkg install python', isPopular: true },
  { id: 'pkg-42', name: 'nodejs', category: 'Development', source: 'pkg', description: 'Runtime JavaScript berbasis V8.', installCommand: 'pkg install nodejs', isPopular: true },
  { id: 'pkg-43', name: 'golang', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman Go oleh Google.', installCommand: 'pkg install golang' },
  { id: 'pkg-44', name: 'rust', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman sistem Rust.', installCommand: 'pkg install rust' },
  { id: 'pkg-45', name: 'clang', category: 'Development', source: 'pkg', description: 'Compiler C/C++ yang modern dan cepat.', installCommand: 'pkg install clang', isPopular: true },
  { id: 'pkg-46', name: 'make', category: 'Development', source: 'pkg', description: 'Alat otomatisasi build proyek.', installCommand: 'pkg install make' },
  { id: 'pkg-47', name: 'cmake', category: 'Development', source: 'pkg', description: 'Sistem build lintas platform.', installCommand: 'pkg install cmake' },
  { id: 'pkg-48', name: 'php', category: 'Development', source: 'pkg', description: 'Interpreter bahasa PHP untuk web.', installCommand: 'pkg install php' },
  { id: 'pkg-49', name: 'ruby', category: 'Development', source: 'pkg', description: 'Interpreter bahasa Ruby.', installCommand: 'pkg install ruby' },
  { id: 'pkg-50', name: 'perl', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman Perl 5.', installCommand: 'pkg install perl' },
  { id: 'pkg-51', name: 'openjdk-17', category: 'Development', source: 'pkg', description: 'Java Development Kit 17.', installCommand: 'pkg install openjdk-17' },
  { id: 'pkg-52', name: 'lua54', category: 'Development', source: 'pkg', description: 'Bahasa skrip Lua versi 5.4.', installCommand: 'pkg install lua54' },
  { id: 'pkg-53', name: 'mariadb', category: 'Development', source: 'pkg', description: 'Server database SQL open source.', installCommand: 'pkg install mariadb' },
  { id: 'pkg-54', name: 'postgresql', category: 'Development', source: 'pkg', description: 'Server database relasional canggih.', installCommand: 'pkg install postgresql' },
  { id: 'pkg-55', name: 'redis', category: 'Development', source: 'pkg', description: 'Penyimpanan struktur data in-memory.', installCommand: 'pkg install redis' },
  { id: 'pkg-56', name: 'git', category: 'Development', source: 'pkg', description: 'Sistem kontrol versi terdistribusi.', installCommand: 'pkg install git', isPopular: true },
  { id: 'pkg-57', name: 'gh', category: 'Development', source: 'pkg', description: 'CLI resmi untuk GitHub.', installCommand: 'pkg install gh' },
  { id: 'pkg-58', name: 'yarn', category: 'Development', source: 'pkg', description: 'Manajer paket JavaScript alternatif.', installCommand: 'pkg install yarn' },
  { id: 'pkg-59', name: 'ninja', category: 'Development', source: 'pkg', description: 'Sistem build kecil dengan fokus kecepatan.', installCommand: 'pkg install ninja' },
  { id: 'pkg-60', name: 'dart', category: 'Development', source: 'pkg', description: 'SDK bahasa pemrograman Dart.', installCommand: 'pkg install dart' },
  { id: 'pkg-61', name: 'elixir', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman dinamis berbasis Erlang.', installCommand: 'pkg install elixir' },
  { id: 'pkg-62', name: 'erlang', category: 'Development', source: 'pkg', description: 'Runtime sistem Erlang.', installCommand: 'pkg install erlang' },
  { id: 'pkg-63', name: 'ocaml', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman fungsional OCaml.', installCommand: 'pkg install ocaml' },
  { id: 'pkg-64', name: 'r-base', category: 'Development', source: 'pkg', description: 'Bahasa untuk komputasi statistik R.', installCommand: 'pkg install r-base' },
  { id: 'pkg-65', name: 'kotlin', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman modern untuk JVM.', installCommand: 'pkg install kotlin' },
  { id: 'pkg-66', name: 'scala', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman berorientasi objek dan fungsional.', installCommand: 'pkg install scala' },
  { id: 'pkg-67', name: 'valac', category: 'Development', source: 'pkg', description: 'Compiler bahasa Vala.', installCommand: 'pkg install valac' },
  { id: 'pkg-68', name: 'zig', category: 'Development', source: 'pkg', description: 'Bahasa pemrograman sistem Zig.', installCommand: 'pkg install zig' },
  { id: 'pkg-69', name: 'tcl', category: 'Development', source: 'pkg', description: 'Interpreter bahasa Tcl.', installCommand: 'pkg install tcl' },
  { id: 'pkg-70', name: 'autoconf', category: 'Development', source: 'pkg', description: 'Alat pembuat skrip konfigurasi otomatis.', installCommand: 'pkg install autoconf' },

  // ==========================================
  // PKG - UTILITY & TOOLS (30)
  // ==========================================
  { id: 'pkg-71', name: 'htop', category: 'Utility', source: 'pkg', description: 'Monitor proses sistem interaktif.', installCommand: 'pkg install htop', isPopular: true },
  { id: 'pkg-72', name: 'btop', category: 'Utility', source: 'pkg', description: 'Monitor sistem modern yang sangat visual.', installCommand: 'pkg install btop', isPopular: true },
  { id: 'pkg-73', name: 'neofetch', category: 'Utility', source: 'pkg', description: 'Alat penampil info sistem yang keren.', installCommand: 'pkg install neofetch', isPopular: true },
  { id: 'pkg-74', name: 'wget', category: 'Utility', source: 'pkg', description: 'Pengunduh file dari web via CLI.', installCommand: 'pkg install wget' },
  { id: 'pkg-75', name: 'curl', category: 'Utility', source: 'pkg', description: 'Alat transfer data dengan URL syntax.', installCommand: 'pkg install curl', isPopular: true },
  { id: 'pkg-76', name: 'aria2', category: 'Utility', source: 'pkg', description: 'Utilitas pengunduhan multi-protokol cepat.', installCommand: 'pkg install aria2' },
  { id: 'pkg-77', name: 'fzf', category: 'Utility', source: 'pkg', description: 'Fuzzy finder baris perintah yang sangat cepat.', installCommand: 'pkg install fzf', isPopular: true },
  { id: 'pkg-78', name: 'bat', category: 'Utility', source: 'pkg', description: 'Pengganti cat dengan syntax highlighting.', installCommand: 'pkg install bat' },
  { id: 'pkg-79', name: 'lsd', category: 'Utility', source: 'pkg', description: 'Perintah ls generasi berikutnya dengan ikon.', installCommand: 'pkg install lsd' },
  { id: 'pkg-80', name: 'fd', category: 'Utility', source: 'pkg', description: 'Alternatif find yang sederhana dan cepat.', installCommand: 'pkg install fd' },
  { id: 'pkg-81', name: 'ripgrep', category: 'Utility', source: 'pkg', description: 'Alat pencarian teks (grep) tercepat.', installCommand: 'pkg install ripgrep' },
  { id: 'pkg-82', name: 'tmux', category: 'Utility', source: 'pkg', description: 'Terminal multiplexer untuk multitasking.', installCommand: 'pkg install tmux', isPopular: true },
  { id: 'pkg-83', name: 'screen', category: 'Utility', source: 'pkg', description: 'Manajer terminal dengan manajemen sesi.', installCommand: 'pkg install screen' },
  { id: 'pkg-84', name: 'zip', category: 'Utility', source: 'pkg', description: 'Alat pengarsipan dan kompresi .zip.', installCommand: 'pkg install zip' },
  { id: 'pkg-85', name: 'unzip', category: 'Utility', source: 'pkg', description: 'Ekstraktor file .zip.', installCommand: 'pkg install unzip' },
  { id: 'pkg-86', name: 'tar', category: 'Utility', source: 'pkg', description: 'Alat pengarsipan file standar GNU.', installCommand: 'pkg install tar' },
  { id: 'pkg-87', name: 'unrar', category: 'Utility', source: 'pkg', description: 'Ekstraktor file .rar.', installCommand: 'pkg install unrar' },
  { id: 'pkg-88', name: 'tree', category: 'Utility', source: 'pkg', description: 'Menampilkan struktur direktori secara rekursif.', installCommand: 'pkg install tree' },
  { id: 'pkg-89', name: 'ncdu', category: 'Utility', source: 'pkg', description: 'Penganalisis penggunaan disk berbasis ncurses.', installCommand: 'pkg install ncdu' },
  { id: 'pkg-90', name: 'toilet', category: 'Utility', source: 'pkg', description: 'Membuat banner teks ASCII berwarna.', installCommand: 'pkg install toilet' },
  { id: 'pkg-91', name: 'figlet', category: 'Utility', source: 'pkg', description: 'Membuat banner teks ASCII besar.', installCommand: 'pkg install figlet' },
  { id: 'pkg-92', name: 'cowsay', category: 'Utility', source: 'pkg', description: 'Sapi berbicara di terminal.', installCommand: 'pkg install cowsay' },
  { id: 'pkg-93', name: 'fortune', category: 'Utility', source: 'pkg', description: 'Menampilkan kutipan keberuntungan acak.', installCommand: 'pkg install fortune' },
  { id: 'pkg-94', name: 'ffmpeg', category: 'Utility', source: 'pkg', description: 'Alat pengolah video dan audio yang sangat kuat.', installCommand: 'pkg install ffmpeg', isPopular: true },
  { id: 'pkg-95', name: 'imagemagick', category: 'Utility', source: 'pkg', description: 'Suite pengolah gambar CLI.', installCommand: 'pkg install imagemagick' },
  { id: 'pkg-96', name: 'graphicsmagick', category: 'Utility', source: 'pkg', description: 'Alternatif ImageMagick yang lebih efisien.', installCommand: 'pkg install graphicsmagick' },
  { id: 'pkg-97', name: 'sox', category: 'Utility', source: 'pkg', description: 'Swiss Army Knife pengolah audio CLI.', installCommand: 'pkg install sox' },
  { id: 'pkg-98', name: 'mpv', category: 'Utility', source: 'pkg', description: 'Pemutar media baris perintah minimalis.', installCommand: 'pkg install mpv' },
  { id: 'pkg-99', name: 'yt-dlp', category: 'Utility', source: 'pkg', description: 'Pengunduh video YouTube dan situs lainnya.', installCommand: 'pkg install yt-dlp', isPopular: true },
  { id: 'pkg-100', name: 'rclone', category: 'Utility', source: 'pkg', description: 'Alat sinkronisasi file untuk penyimpanan cloud.', installCommand: 'pkg install rclone' },

  // ==========================================
  // PIP - WEB & APIS (30)
  // ==========================================
  { id: 'pip-1', name: 'requests', category: 'Python Library', source: 'pip', description: 'Library HTTP untuk manusia.', installCommand: 'pip install requests', isPopular: true },
  { id: 'pip-2', name: 'flask', category: 'Python Library', source: 'pip', description: 'Microframework web yang ringan.', installCommand: 'pip install flask', isPopular: true },
  { id: 'pip-3', name: 'django', category: 'Python Library', source: 'pip', description: 'Framework web lengkap untuk profesional.', installCommand: 'pip install django' },
  { id: 'pip-4', name: 'fastapi', category: 'Python Library', source: 'pip', description: 'Framework API modern yang sangat cepat.', installCommand: 'pip install fastapi', isPopular: true },
  { id: 'pip-5', name: 'uvicorn', category: 'Python Library', source: 'pip', description: 'Server ASGI secepat kilat untuk Python.', installCommand: 'pip install uvicorn' },
  { id: 'pip-6', name: 'aiohttp', category: 'Python Library', source: 'pip', description: 'Klien/Server HTTP asinkron.', installCommand: 'pip install aiohttp' },
  { id: 'pip-7', name: 'beautifulsoup4', category: 'Python Library', source: 'pip', description: 'Library untuk web scraping HTML/XML.', installCommand: 'pip install beautifulsoup4', isPopular: true },
  { id: 'pip-8', name: 'scrapy', category: 'Python Library', source: 'pip', description: 'Framework scraping tingkat tinggi yang kuat.', installCommand: 'pip install scrapy' },
  { id: 'pip-9', name: 'selenium', category: 'Python Library', source: 'pip', description: 'Otomatisasi browser web.', installCommand: 'pip install selenium' },
  { id: 'pip-10', name: 'playwright', category: 'Python Library', source: 'pip', description: 'Otomatisasi browser modern oleh Microsoft.', installCommand: 'pip install playwright' },
  { id: 'pip-11', name: 'httpx', category: 'Python Library', source: 'pip', description: 'Klien HTTP generasi berikutnya yang mendukung async.', installCommand: 'pip install httpx' },
  { id: 'pip-12', name: 'urllib3', category: 'Python Library', source: 'pip', description: 'Klien HTTP yang kuat dan aman.', installCommand: 'pip install urllib3' },
  { id: 'pip-13', name: 'gunicorn', category: 'Python Library', source: 'pip', description: 'Server HTTP WSGI untuk Python.', installCommand: 'pip install gunicorn' },
  { id: 'pip-14', name: 'starlette', category: 'Python Library', source: 'pip', description: 'Framework ASGI yang ringan untuk membangun layanan.', installCommand: 'pip install starlette' },
  { id: 'pip-15', name: 'pydantic', category: 'Python Library', source: 'pip', description: 'Validasi data menggunakan tipe Python.', installCommand: 'pip install pydantic' },
  { id: 'pip-16', name: 'marshmallow', category: 'Python Library', source: 'pip', description: 'Serialisasi/deserialisasi objek kompleks.', installCommand: 'pip install marshmallow' },
  { id: 'pip-17', name: 'celery', category: 'Python Library', source: 'pip', description: 'Antrian tugas terdistribusi asinkron.', installCommand: 'pip install celery' },
  { id: 'pip-18', name: 'redis', category: 'Python Library', source: 'pip', description: 'Antarmuka Python untuk database Redis.', installCommand: 'pip install redis' },
  { id: 'pip-19', name: 'motor', category: 'Python Library', source: 'pip', description: 'Driver MongoDB asinkron untuk Python.', installCommand: 'pip install motor' },
  { id: 'pip-20', name: 'pymongo', category: 'Python Library', source: 'pip', description: 'Driver resmi MongoDB untuk Python.', installCommand: 'pip install pymongo' },
  { id: 'pip-21', name: 'sqlalchemy', category: 'Python Library', source: 'pip', description: 'Toolkit SQL dan Object Relational Mapper.', installCommand: 'pip install sqlalchemy' },
  { id: 'pip-22', name: 'peewee', category: 'Python Library', source: 'pip', description: 'ORM kecil dan ekspresif.', installCommand: 'pip install peewee' },
  { id: 'pip-23', name: 'databases', category: 'Python Library', source: 'pip', description: 'Dukungan database asinkron untuk Python.', installCommand: 'pip install databases' },
  { id: 'pip-24', name: 'jwt', category: 'Python Library', source: 'pip', description: 'Implementasi JSON Web Token di Python.', installCommand: 'pip install PyJWT' },
  { id: 'pip-25', name: 'python-jose', category: 'Python Library', source: 'pip', description: 'Implementasi JOSE untuk Python.', installCommand: 'pip install python-jose' },
  { id: 'pip-26', name: 'passlib', category: 'Python Library', source: 'pip', description: 'Library hashing password yang komprehensif.', installCommand: 'pip install passlib' },
  { id: 'pip-27', name: 'bcrypt', category: 'Python Library', source: 'pip', description: 'Library hashing modern berbasis bcrypt.', installCommand: 'pip install bcrypt' },
  { id: 'pip-28', name: 'itsdangerous', category: 'Python Library', source: 'pip', description: 'Mengirim data ke lingkungan tidak terpercaya dengan aman.', installCommand: 'pip install itsdangerous' },
  { id: 'pip-29', name: 'python-multipart', category: 'Python Library', source: 'pip', description: 'Parsing form data multipart untuk Python.', installCommand: 'pip install python-multipart' },
  { id: 'pip-30', name: 'fastapi-users', category: 'Python Library', source: 'pip', description: 'Sistem registrasi dan otentikasi siap pakai untuk FastAPI.', installCommand: 'pip install fastapi-users' },

  // ==========================================
  // PIP - DATA & SCIENCE (30)
  // ==========================================
  { id: 'pip-31', name: 'numpy', category: 'Python Library', source: 'pip', description: 'Komputasi matriks dan array tingkat tinggi.', installCommand: 'pip install numpy', isPopular: true },
  { id: 'pip-32', name: 'pandas', category: 'Python Library', source: 'pip', description: 'Manipulasi dan analisis data yang kuat.', installCommand: 'pip install pandas', isPopular: true },
  { id: 'pip-33', name: 'matplotlib', category: 'Python Library', source: 'pip', description: 'Library visualisasi data 2D.', installCommand: 'pip install matplotlib' },
  { id: 'pip-34', name: 'seaborn', category: 'Python Library', source: 'pip', description: 'Visualisasi data statistik berbasis matplotlib.', installCommand: 'pip install seaborn' },
  { id: 'pip-35', name: 'scipy', category: 'Python Library', source: 'pip', description: 'Library untuk komputasi ilmiah dan teknik.', installCommand: 'pip install scipy' },
  { id: 'pip-36', name: 'scikit-learn', category: 'Python Library', source: 'pip', description: 'Library Machine Learning untuk Python.', installCommand: 'pip install scikit-learn' },
  { id: 'pip-37', name: 'statsmodels', category: 'Python Library', source: 'pip', description: 'Pemodelan statistik dan ekonometrika.', installCommand: 'pip install statsmodels' },
  { id: 'pip-38', name: 'tensorflow', category: 'Python Library', source: 'pip', description: 'Platform Machine Learning open source.', installCommand: 'pip install tensorflow' },
  { id: 'pip-39', name: 'torch', category: 'Python Library', source: 'pip', description: 'Framework Deep Learning dari Facebook.', installCommand: 'pip install torch' },
  { id: 'pip-40', name: 'keras', category: 'Python Library', source: 'pip', description: 'API Deep Learning tingkat tinggi.', installCommand: 'pip install keras' },
  { id: 'pip-41', name: 'opencv-python', category: 'Python Library', source: 'pip', description: 'Library Computer Vision untuk Python.', installCommand: 'pip install opencv-python' },
  { id: 'pip-42', name: 'pillow', category: 'Python Library', source: 'pip', description: 'Library pengolah gambar Python (PIL fork).', installCommand: 'pip install pillow' },
  { id: 'pip-43', name: 'nltk', category: 'Python Library', source: 'pip', description: 'Toolkit pemrosesan bahasa alami (NLP).', installCommand: 'pip install nltk' },
  { id: 'pip-44', name: 'spacy', category: 'Python Library', source: 'pip', description: 'NLP industri tingkat lanjut.', installCommand: 'pip install spacy' },
  { id: 'pip-45', name: 'gensim', category: 'Python Library', source: 'pip', description: 'Pemodelan topik dan analisis teks.', installCommand: 'pip install gensim' },
  { id: 'pip-46', name: 'plotly', category: 'Python Library', source: 'pip', description: 'Library grafik interaktif.', installCommand: 'pip install plotly' },
  { id: 'pip-47', name: 'bokeh', category: 'Python Library', source: 'pip', description: 'Visualisasi interaktif untuk browser.', installCommand: 'pip install bokeh' },
  { id: 'pip-48', name: 'dash-plotly', category: 'Python Library', source: 'pip', description: 'Framework web untuk aplikasi data.', installCommand: 'pip install dash' },
  { id: 'pip-49', name: 'streamlit', category: 'Python Library', source: 'pip', description: 'Membangun aplikasi data dengan cepat.', installCommand: 'pip install streamlit', isPopular: true },
  { id: 'pip-50', name: 'jupyterlab', category: 'Python Library', source: 'pip', description: 'Lingkungan komputasi interaktif berbasis web.', installCommand: 'pip install jupyterlab' },
  { id: 'pip-51', name: 'notebook', category: 'Python Library', source: 'pip', description: 'Classic Jupyter Notebook.', installCommand: 'pip install notebook' },
  { id: 'pip-52', name: 'joblib', category: 'Python Library', source: 'pip', description: 'Komputasi paralel dan caching.', installCommand: 'pip install joblib' },
  { id: 'pip-53', name: 'dask', category: 'Python Library', source: 'pip', description: 'Komputasi paralel skala besar.', installCommand: 'pip install dask' },
  { id: 'pip-54', name: 'networkx', category: 'Python Library', source: 'pip', description: 'Studi jaringan dan grafik kompleks.', installCommand: 'pip install networkx' },
  { id: 'pip-55', name: 'sympy', category: 'Python Library', source: 'pip', description: 'Matematika simbolik untuk Python.', installCommand: 'pip install sympy' },
  { id: 'pip-56', name: 'scikit-image', category: 'Python Library', source: 'pip', description: 'Pemrosesan gambar ilmiah.', installCommand: 'pip install scikit-image' },
  { id: 'pip-57', name: 'tabulate', category: 'Python Library', source: 'pip', description: 'Mencetak data tabular dengan indah.', installCommand: 'pip install tabulate' },
  { id: 'pip-58', name: 'openpyxl', category: 'Python Library', source: 'pip', description: 'Membaca/menulis file Excel (xlsx).', installCommand: 'pip install openpyxl' },
  { id: 'pip-59', name: 'xlrd', category: 'Python Library', source: 'pip', description: 'Membaca data dari file Excel lama (xls).', installCommand: 'pip install xlrd' },
  { id: 'pip-60', name: 'h5py', category: 'Python Library', source: 'pip', description: 'Antarmuka untuk format data HDF5.', installCommand: 'pip install h5py' },

  // ==========================================
  // PIP - CLI TOOLS & UTILS (40)
  // ==========================================
  { id: 'pip-61', name: 'click', category: 'Python Library', source: 'pip', description: 'Toolkit pembuat antarmuka CLI yang indah.', installCommand: 'pip install click', isPopular: true },
  { id: 'pip-62', name: 'typer', category: 'Python Library', source: 'pip', description: 'CLI berbasis type hints dari pencipta FastAPI.', installCommand: 'pip install typer', isPopular: true },
  { id: 'pip-63', name: 'rich', category: 'Python Library', source: 'pip', description: 'Teks kaya (warna, tabel, progress bar) di terminal.', installCommand: 'pip install rich', isPopular: true },
  { id: 'pip-64', name: 'prompt-toolkit', category: 'Python Library', source: 'pip', description: 'Membangun aplikasi baris perintah interaktif.', installCommand: 'pip install prompt-toolkit' },
  { id: 'pip-65', name: 'colorama', category: 'Python Library', source: 'pip', description: 'Output teks berwarna lintas platform.', installCommand: 'pip install colorama' },
  { id: 'pip-66', name: 'tqdm', category: 'Python Library', source: 'pip', description: 'Progress bar pintar untuk loop.', installCommand: 'pip install tqdm', isPopular: true },
  { id: 'pip-67', name: 'python-dotenv', category: 'Python Library', source: 'pip', description: 'Memuat variabel lingkungan dari file .env.', installCommand: 'pip install python-dotenv' },
  { id: 'pip-68', name: 'pyyaml', category: 'Python Library', source: 'pip', description: 'Parser dan emiter YAML untuk Python.', installCommand: 'pip install pyyaml' },
  { id: 'pip-69', name: 'toml', category: 'Python Library', source: 'pip', description: 'Library untuk parsing file TOML.', installCommand: 'pip install toml' },
  { id: 'pip-70', name: 'configparser', category: 'Python Library', source: 'pip', description: 'Menangani file konfigurasi INI.', installCommand: 'pip install configparser' },
  { id: 'pip-71', name: 'watchdog', category: 'Python Library', source: 'pip', description: 'Memantau perubahan sistem file secara real-time.', installCommand: 'pip install watchdog' },
  { id: 'pip-72', name: 'schedule', category: 'Python Library', source: 'pip', description: 'Penjadwalan tugas Python yang ramah manusia.', installCommand: 'pip install schedule' },
  { id: 'pip-73', name: 'fabric', category: 'Python Library', source: 'pip', description: 'Eksekusi perintah remote dan deployment via SSH.', installCommand: 'pip install fabric' },
  { id: 'pip-74', name: 'invoke', category: 'Python Library', source: 'pip', description: 'Eksekusi tugas dan manajemen tugas lokal.', installCommand: 'pip install invoke' },
  { id: 'pip-75', name: 'ansible', category: 'Python Library', source: 'pip', description: 'Sistem otomatisasi IT yang sangat populer.', installCommand: 'pip install ansible' },
  { id: 'pip-76', name: 'paramiko', category: 'Python Library', source: 'pip', description: 'Implementasi protokol SSHv2 Python.', installCommand: 'pip install paramiko' },
  { id: 'pip-77', name: 'cryptography', category: 'Python Library', source: 'pip', description: 'Resep kriptografi tingkat tinggi dan primitif.', installCommand: 'pip install cryptography' },
  { id: 'pip-78', name: 'pyopenssl', category: 'Python Library', source: 'pip', description: 'Wrapper Python untuk library OpenSSL.', installCommand: 'pip install pyopenssl' },
  { id: 'pip-79', name: 'scapy', category: 'Python Library', source: 'pip', description: 'Manipulasi paket jaringan interaktif.', installCommand: 'pip install scapy' },
  { id: 'pip-80', name: 'telethon', category: 'Python Library', source: 'pip', description: 'Klien Telegram API MTProto.', installCommand: 'pip install telethon' },
  { id: 'pip-81', name: 'pyrogram', category: 'Python Library', source: 'pip', description: 'Framework Telegram modern dan asinkron.', installCommand: 'pip install pyrogram' },
  { id: 'pip-82', name: 'python-telegram-bot', category: 'Python Library', source: 'pip', description: 'Wrapper Python untuk Telegram Bot API.', installCommand: 'pip install python-telegram-bot' },
  { id: 'pip-83', name: 'discord.py', category: 'Python Library', source: 'pip', description: 'API wrapper untuk Discord di Python.', installCommand: 'pip install discord.py' },
  { id: 'pip-84', name: 'tweepy', category: 'Python Library', source: 'pip', description: 'Library Python untuk akses Twitter API.', installCommand: 'pip install tweepy' },
  { id: 'pip-85', name: 'pygments', category: 'Python Library', source: 'pip', description: 'Generic syntax highlighter.', installCommand: 'pip install pygments' },
  { id: 'pip-86', name: 'markdown', category: 'Python Library', source: 'pip', description: 'Implementasi Python dari John Gruber Markdown.', installCommand: 'pip install markdown' },
  { id: 'pip-87', name: 'jinja2', category: 'Python Library', source: 'pip', description: 'Mesin template modern dan ramah desainer.', installCommand: 'pip install jinja2' },
  { id: 'pip-88', name: 'faker', category: 'Python Library', source: 'pip', description: 'Menghasilkan data palsu untuk testing.', installCommand: 'pip install faker' },
  { id: 'pip-89', name: 'pytest', category: 'Python Library', source: 'pip', description: 'Framework pengujian Python yang matang.', installCommand: 'pip install pytest' },
  { id: 'pip-90', name: 'tox', category: 'Python Library', source: 'pip', description: 'Otomatisasi pengujian di berbagai versi Python.', installCommand: 'pip install tox' },
  { id: 'pip-91', name: 'coverage', category: 'Python Library', source: 'pip', description: 'Alat pengukur cakupan kode pengujian.', installCommand: 'pip install coverage' },
  { id: 'pip-92', name: 'black', category: 'Python Library', source: 'pip', description: 'Pemformat kode Python yang tanpa kompromi.', installCommand: 'pip install black' },
  { id: 'pip-93', name: 'flake8', category: 'Python Library', source: 'pip', description: 'Pemeriksa gaya kode Python (PEP8).', installCommand: 'pip install flake8' },
  { id: 'pip-94', name: 'pylint', category: 'Python Library', source: 'pip', description: 'Penganalisa statis untuk kode Python.', installCommand: 'pip install pylint' },
  { id: 'pip-95', name: 'mypy', category: 'Python Library', source: 'pip', description: 'Static type checker opsional untuk Python.', installCommand: 'pip install mypy' },
  { id: 'pip-96', name: 'poetry', category: 'Python Library', source: 'pip', description: 'Manajer dependensi dan packaging Python modern.', installCommand: 'pip install poetry' },
  { id: 'pip-97', name: 'pipenv', category: 'Python Library', source: 'pip', description: 'Alur kerja packaging Python untuk manusia.', installCommand: 'pip install pipenv' },
  { id: 'pip-98', name: 'virtualenv', category: 'Python Library', source: 'pip', description: 'Alat untuk membuat lingkungan Python terisolasi.', installCommand: 'pip install virtualenv' },
  { id: 'pip-99', name: 'pyinstaller', category: 'Python Library', source: 'pip', description: 'Membundel aplikasi Python menjadi executable mandiri.', installCommand: 'pip install pyinstaller' },
  { id: 'pip-100', name: 'shiv', category: 'Python Library', source: 'pip', description: 'Membuat file zip executable Python (zipapps).', installCommand: 'pip install shiv' },
  { id: 'pip-101', name: 'sh', category: 'Python Library', source: 'pip', description: 'Memanggil program apapun seolah itu fungsi Python.', installCommand: 'pip install sh' },
  { id: 'pip-102', name: 'pexpect', category: 'Python Library', source: 'pip', description: 'Otomatisasi aplikasi interaktif terminal.', installCommand: 'pip install pexpect' },
  { id: 'pip-103', name: 'python-magic', category: 'Python Library', source: 'pip', description: 'Identifikasi tipe file menggunakan libmagic.', installCommand: 'pip install python-magic' },
  { id: 'pip-104', name: 'loguru', category: 'Python Library', source: 'pip', description: 'Logging Python menjadi sangat menyenangkan.', installCommand: 'pip install loguru' },
  { id: 'pip-105', name: 'icecream', category: 'Python Library', source: 'pip', description: 'Alat debugging pengganti print().', installCommand: 'pip install icecream' }
];
